apiVersion: v1
kind: Service
metadata:
  name: googly-login-service
spec:
  type: NodePort
  selector:
    app: googly-login-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000

